### ISSUE TITLE
As a developer I want Hydrate to scaffold a manifests directory and add namespace yaml file

### ISSUE THREAD

**Issue by andrebriggs** [microsoft/hydrate#20]
As a developer I want a place to put my namespace yams files. The Hydrate tool should create a `manifests` directory in the `component.yaml` output to support this. The tool should also tell me what I should guide me about what I should put inside of this directory.

Example:

<pre>
name: "cloud-native"
generator: "static"
<b>path: "./manifests"</b>
subcomponents:
  - name: "elasticsearch-fluentd-kibana"
    source: "../fabrikate-elasticsearch-fluentd-kibana"
  - name: "prometheus-grafana"
    source: "../fabrikate-prometheus-grafana"
  - name: "istio"
    source: "../fabrikate-istio"
  - name: "kured"
    source: "../fabrikate-kured"
</pre>

**Comment by samiyaakhtar** [comment]
An example is [here](https://github.com/microsoft/fabrikate-definitions/blob/master/definitions/fabrikate-istio/manifests/istio-namespace.yaml)

**Comment by andrewDoing** [comment]
To clarify, this issue involves the following steps (correct me if I'm wrong)

- [ ] Add the path: "./manifests" attribute to the component.yaml file

- [ ] Create manifests directory

- [ ] Generate namespaces.yaml files in the ./manifests directory
