### ISSUE TITLE
Investigate command line option for kubecontext

### ISSUE THREAD

**Issue by edaena** [microsoft/hydrate#25]
Investigate adding a flag to allow the user to select what kubecontext they want to connect to.

**Comment by andrewDoing** [comment]
When a kubeconfig file is passed to Hydrate that contains config info for multiple clusters, Hydrate will connect to the cluster that is set as the current context.

So as long as the kubeconfig file's current cluster context is set to the cluster that you want to Hydrate, it will work on that cluster.

@edaena good to close?
